---
- hosts: php
  sudo: yes

  tasks:

  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - apache2
      - libapache2-mod-php7.0
      - php7.0
      - php7.0-mcrypt
      - php7.0-mysql
      - php7.0-json
      - php7.0-curl
      - php7.0-mbstring
      - mysql-server

  - name: install composer
    shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    args:
      creates: /usr/local/bin/composer

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
